[package]
name = "gallerust"
version = "0.1.0"
edition = "2021"

[dependencies]
adw = {package = "libadwaita", version = "0.7.1", features = ["v1_4"]}
env_logger = "0.11.5"
log = "0.4.22"
relm4 = {version = "0.9.1", features = ["libadwaita"]}
relm4-components = "0.9.1"
relm4-icons = "0.9.0"
